### ISSUE TITLE
Tag v0.1.3 missing

### ISSUE THREAD

**Issue by dotlambda** [pburgio/iottyCloud#1]
Version 0.1.3 exists on [PyPI](https://pypi.org/project/iottycloud/#history) but not on [GitHub](https://github.com/pburgio/iottyCloud/tags).

**Comment by pburgio** [comment]
Done

**Comment by dotlambda** [comment]
You tagged the wrong commit. It should have been c328cc497bf58a1da148ea88e309129177d69af0.

**Comment by pburgio** [comment]
> You tagged the wrong commit. It should have been [c328cc4](https://github.com/pburgio/iottyCloud/commit/c328cc497bf58a1da148ea88e309129177d69af0).

Sorry. Done.

**Comment by dotlambda** [comment]
Now there are no tags 0.2.0 and 0.2.1.

**Comment by pburgio** [comment]
> Now there are no tags 0.2.0 and 0.2.1.

@shapournemati-iotty can you kindly address this?

**Comment by shapournemati-iotty** [comment]
Hi, I have added the tags, however they are on the same commit as the publishing of the version 0.2.0 had an issue and the local commit has been amended in favour of version 0.2.1

**Comment by dotlambda** [comment]
Tag v0.3.0 is also missing.

**Comment by mweinelt** [comment]
Can you please add the missing v0.3.0 tag? :pleading_face:

**Comment by shapournemati-iotty** [comment]
> Tag v0.3.0 is also missing.

Hi, here it is!

https://github.com/pburgio/iottyCloud/releases/tag/0.3.0
